all:
   .general:
       salt: mySecret$alt
       yearRangeMin: 1700
       yearRangeMax: <?php echo date('Y')+2; ?>

       dateUpperBound: '2038/12/31'
       dateLowerBound: '0001/01/01'
       yearUpperBound: '2038'
       recPerPage: 10
       pagerSlidingSize: 5
       catalogueRecLimit: 200
       queryTimeout: 30000

   broadcast:
       enabled: true
       message: This is a demo application. Data is restored nightly !
       submessage: login with user/user or encoder/encoder or admin/admin
#dev:
   tracking:
       enabled: true
   mailer:
       sender: collections@naturalsciences.be
