config/darwin.yml:
  class:    sfDefineEnvironmentConfigHandler
  param:
    prefix: dw_

data/feed/help_widgets.yml:
#  class:    helpWidgetConfigHandler
  class:    sfDefineEnvironmentConfigHandler
  param:
    prefix: widget_
